# Resources:
# - https://packaging.python.org/en/latest/guides/writing-pyproject-toml
# - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tkt"
requires-python = ">= 3.12"
description = "Tkinter Toys (TKT)"
version = "0"

[tool.setuptools]
packages = ["tkt"]
